spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/mymdb
    username: mymdbAdmin
    password: pgpwd4mymdb
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
