name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-test:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: "mymdb"
          POSTGRES_USER: "mymdbAdmin"
          POSTGRES_PASSWORD: "pgpwd4mymdb"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3  # setup adopt-hotspot jdk 17
        with:
          java-version: '17'
          distribution: 'adopt-hotspot'

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2 # setup gradle and use a wrapper
        with:
          gradle-version: wrapper

      - name: Make gradlew executable
        run: chmod +x ./gradlew            # make ./gradlew an executable command for Linux

      - name: Execute checkstyle
        run: ./gradlew checkstyleMain     # run gradle checkstyle

      - name: Run tests
        run: ./gradlew clean build test    # run gradle tasks: clean, test and build

      - name: Run Coverage
        run: ./gradlew jacocoTestReport

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.2
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 80
